import type { Metadata } from "next";
import { sansation, ibmPlexSerif } from "@/styles/fonts";
import "@/styles/tokens.css";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sansation.variable} ${ibmPlexSerif.variable}`}>
        {children}
      </body>
    </html>
  );
}
